version: "3.8"

services:
  strapi:
    # image: strapi/strapi
    build: 
      context: .
      args:
        BASE_VERSION: latest
        STRAPI_VERSION: 4.0.2
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-strapi}
      DATABASE_HOST: ${DATABASE_HOST:-db}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-strapi}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      NODE_ENV: ${NODE_ENV}
      DUMP_VERSION: ${DUMP_VERSION}
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
      - ./config-dumps-files:/srv/config-dumps-files
    ports:
      - "1337:1337"
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13.3-alpine
    restart: always
    env_file: .env
    networks:
      - strapi-app-network
    volumes:
      # - ./db:/var/lib/postgresql/data
      # - /tmp:/tmp
      # - strapidata:/data/db
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-strapi}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-strapi}
      POSTGRES_DB: ${DATABASE_NAME:-strapi}
    ports:
      - "5432:5432"
    expose:
      - "5432"
  
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-strapi}
    networks:
      - strapi-app-network
    ports: 
        - "16543:80"
    depends_on: 
        - db

networks:
  strapi-app-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin: